In [1]:
import pandas as pd

df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

**Setting messing review rating values(NULLs) with the median of the cattegory.**. 

Why not average? because mean is more accurate than avarage

Reference: 
- The Art of Statistics: How to Learn from Data" - David Spiegelhalter

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

**Feature engineering** create column `age_group`

In [11]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [12]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

**Feature engineering** create column `purchase_frequency_days`

In [13]:
frequency_mapping = {
    'Fortnightly':14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [14]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

**Does all applied discounts use promo code?**

mantain both discount_applied and promo_code_used is redundante?

In [15]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In this case is true, we wil remove one of them. But, in a real scenario, is not always true.
It will depend on business rules

In [17]:
df = df.drop('promo_code_used', axis=1)

In [18]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

Next, I will put the csv inside a Database.

`apt install postgresql`

### Install PostgreSQL
  - Update your package list: `sudo apt update`
  - Install PostgreSQL and the companion tools: `sudo apt install -y postgresql postgresql-contrib`
  - Make sure the service is running: `sudo systemctl start postgresql`
  - Enable it to start automatically on boot: `sudo systemctl enable postgresql`
### Access the Database
- Switch to the default system user named postgres: `sudo -i -u postgres`
- Open the SQL command prompt: `psql`
- Close the prompt when finished: \q
### Basic Commands
- Create a new database: `CREATE DATABASE mydatabase`;
- List all databases: `\l`
- Connect to a specific database: `\c mydatabase`
- Create a new user with a password: `CREATE USER myuser WITH ENCRYPTED PASSWORD 'mypassword'`;

**Install addtional packages to connect to database.**

`pip install psycopg2-binary sqlalchemy`

**Connect to Database and send dataframe to postgresql**

In [19]:
from sqlalchemy import create_engine, text

username = "postgres"
password = "1234"
host = "localhost"
port = "5432"
database = "customer_behavior"

DATABASE_URL = f"postgresql://postgres:{password}@{host}/{database}"

engine = create_engine(DATABASE_URL)

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data sucessfully loaded into table {table_name} in database {database}")

Data sucessfully loaded into table customer in database customer_behavior

## Business Analysis using SQL

Questions:
- Q1. What is the total revenue generated by male vs. female customers?
```SQL
    SELECT gender, SUM(purchase_amount) AS revenue 
    FROM customer 
    GROUP BY gender;
```
- Q2. Which customers used a discount but still spent more than the average purchase amount?
  ```SQL
        SELECT customer_id, purchase_amount
        FROM customer
        WHERE discount_applied = 'Yes'
        AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
  ```
- Q3. Which are the top 5 products with the highest average review rating?
```SQL
    SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC, 2) AS "Average Product Rating"
    FROM customer
    GROUP BY item_purchased
    ORDER BY AVG(review_rating) DESC
    LIMIT 5;
```
- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
```SQL
   SELECT shipping_type, ROUND(AVG(purchase_amount)::NUMERIC, 2)
   FROM customer
   WHERE shipping_type in ('Standard', 'Express')
   GROUP BY shipping_type;

   --- Median
   SELECT shipping_type, percentile_cont(0.5) WITHIN GROUP(
    ORDER BY purchase_amount
   ) AS median_purchase_amount
   FROM customer
   WHERE shipping_type in ('Standard', 'Express')
   GROUP BY shipping_type;
```
- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
```SQL
    SELECT subscription_status,
    COUNT(DISTINCT customer_id) AS total_customers,
    ROUND(AVG(purchase_amount)::NUMERIC, 2) AS  avg_spend, 
    SUM(purchase_amount) AS total_revenue
    FROM customer
    GROUP BY subscription_status
    ORDER BY total_revenue, avg_spend DESC;
```
- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
```SQL
    SELECT item_purchased, 
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
    / COUNT(*), 2
    ) AS discount_rate
    FROM customer
    GROUP BY item_purchased
    ORDER BY discount_rate DESC
    LIMIT 5;
```
- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
```SQL
    WITH customer_type AS (
        SELECT customer_id, previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
        FROM customer
    )
    SELECT customer_segment, COUNT(*) AS "Number of Customers"
    FROM  customer_type
    GROUP BY customer_segment;


    -- My approach, is not a good ideia because the database can too small values
    -- for previous_purchases, and this aproach can consider an customer with
    -- 3 or 5 previous purchases as Loyal
    WITH percentiles AS (
        SELECT
            percentile_cont(0.25)
                WITHIN GROUP (ORDER BY previous_purchases) AS p25,
            percentile_cont(0.50)
                WITHIN GROUP (ORDER BY previous_purchases) AS p50
        FROM customer
    )
    SELECT
        customer_id,
        CASE
            WHEN previous_purchases <= (SELECT p25 FROM percentiles) THEN 'New'
            WHEN previous_purchases <= (SELECT p50 FROM percentiles) THEN 'Returning'
            ELSE 'Loyal'
        END AS segment
    FROM customer;
```
- Q8. What are the top 3 most purchased products within each category?
```SQL
    WITH item_counts AS(
        SELECT category,
        item_purchased, COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
            ) AS item_rank
        FROM customer
        GROUP BY category, item_purchased
    )
    SELECT item_rank, category, item_purchased, total_orders
    FROM item_counts
    WHERE item_rank <=3;
```
- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
```SQL
    SELECT subscription_status,
            COUNT(customer_id) AS repeated_buyers
            FROM customer
            WHERE previous_purchases > 5
            GROUP BY subscription_status;

    -- My approach
    WITH repeat_buyers AS (
        SELECT customer_id, subscription_status
        FROM customer
        WHERE previous_purchases > 5
    )
    SELECT subscription_status, ROUND(100.0 * COUNT(customer_id)/(SELECT COUNT(*) FROM repeat_buyers),2)
    FROM customer
    GROUP BY subscription_status
```
- Q10. What is the revenue contribution of each age group?
```SQL
    SELECT age_group, SUM(purchase_amount) AS revenue
        FROM customer
        GROUP BY age_group
        ORDER BY revenue DESC;
```